services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    networks:
      - infra-network
    volumes:
      - n8n:/home/node/.n8n
    environment:
      - OLLAMA_HOST=ollama:11434
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db-n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_db
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_password
    depends_on:
      - db-n8n

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - infra-network
    # Comment the following lines to disable GPU support
    deploy:
      resources:
        limits:
          cpus: '15.0'  # Limits the container to the power of 15 cores
        reservations:
          devices:
            - driver: nvidia
              count: all        # Use all available GPUs
              capabilities: [gpu]

  ollama-pull:
    image: ollama/ollama:latest
    container_name: ollama-pull
    networks:
      - infra-network
    environment:
      - OLLAMA_HOST=ollama:11434
    depends_on:
      - ollama
    entrypoint: /bin/sh
    command: -c "sleep 5; ollama pull llama3.2"

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    networks:
      - infra-network
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
    depends_on:
      - db-fun
    volumes:
      - superset_home:/app/superset_home

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      # Initial Admin Credentials
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Database Config
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password123
      # Dev settings
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - infra-network

networks:
  infra-network:
    external: true

volumes:
  n8n:
    external: true
  ollama:
    external: true
  superset_home:
    external: true